const D=window.STUDY_DATA;
const A=document.getElementById('app');
let state={pack:null,view:'home',quiz:null,flashIndex:0,flashFlip:false,manageFilter:'all',editingId:null};

const GO_TITLES={
  '201':'Response to Resistance','202':'Firearms','203':'Less-Lethal Munitions','210':'Arrests, Stops, and Frisks','211':'Prisoner Care','214':'Vehicle Pursuits','215':'Critical Incidents','219':'Search and Seizure','221':'Workplace Harassment','223':'Internal Complaint Process','225':'Police Related Death or Injury','227':'Missing/Endangered Persons','303':'Emergency Notification and Call Out','309':'Department Computer Operations','401':'Professional Conduct','412':'Grooming and Appearance','501':'Response to Calls for Service','502':'Call Handling and Preliminary Investigation','513':'Mobile Video Recording System (MVRS)','709':'Critical Incident Stress Management'
};

const load=()=>JSON.parse(localStorage.getItem('studyforge-progress')||'{}');
const save=p=>localStorage.setItem('studyforge-progress',JSON.stringify(p));
const P=()=>load();
const loadCustom=()=>JSON.parse(localStorage.getItem('studyforge-custom-data')||'{}');
const saveCustom=x=>localStorage.setItem('studyforge-custom-data',JSON.stringify(x));

function goLabel(value){
  const m=String(value||'').match(/GO\s*(\d+)/i);
  if(!m) return value;
  const title=GO_TITLES[m[1]];
  return title?`GO ${m[1]} – ${title}`:value;
}
function decorateSergeantQuestion(q){
  if(q.pack!=='sergeant') return {...q};
  let qq={...q};
  const m=String(qq.category||qq.source||'').match(/GO\s*(\d+)/i);
  if(m&&GO_TITLES[m[1]]){
    const full=`GO ${m[1]} – ${GO_TITLES[m[1]]}`;
    qq.category=full;
    if(/^GO\s*\d+$/i.test(String(qq.source||'').trim())) qq.source=full;
    qq.question=String(qq.question||'').replace(new RegExp(`According to\\s+GO\\s*${m[1]}(?=\\s*[,–-])`,'i'),`According to ${full}`);
  }
  return qq;
}
function allQuestions(packId){
  const base=D.packs[packId].questions||[];
  const c=loadCustom()[packId]||{added:[],overrides:{},disabled:[]};
  const disabled=new Set(c.disabled||[]);
  const merged=base.filter(q=>!disabled.has(q.id)).map(q=>c.overrides&&c.overrides[q.id]?{...q,...c.overrides[q.id]}:q).concat(c.added||[]);
  return merged.map(decorateSergeantQuestion);
}
function packData(id){return {...D.packs[id],questions:allQuestions(id)}}
function packProgress(id){const p=P()[id]||{};const attempts=p.attempts||[];const total=attempts.length;const correct=attempts.filter(x=>x.correct).length;return {total,correct,pct:total?Math.round(correct/total*100):0,missed:[...new Set((p.missed||[]))]}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function jsEsc(s){return String(s??'').replace(/\\/g,'\\\\').replace(/'/g,"\\'")}

function home(){state.pack=null;state.view='home';const cards=Object.entries(D.packs).map(([id,p0])=>{let p=packData(id),s=packProgress(id);return `<div class="card pack" onclick="openPack('${id}')"><div><span class="pill">${p.questions.length} question bank</span><h2>${esc(p.title)}</h2><div class="muted">${esc(p.subtitle)}</div></div><div><div class="row"><div><div class="tag">Mastery</div><div class="metric">${s.pct}%</div></div><div style="flex:1"><div class="tag">${s.total} answered</div><div class="progress"><span style="width:${s.pct}%"></span></div></div></div></div></div>`}).join('');A.innerHTML=`<main class="shell"><div class="top"><div><div class="brand">StudyForge</div><div class="tag">Your private, offline study center</div></div><span class="pill">Version 2</span></div><h1 class="section-title">Choose a study pack</h1><p class="muted">Study, drill definitions, take practice quizzes, manage your question bank, and automatically revisit weak areas.</p><div class="grid">${cards}</div><div class="card" style="margin-top:16px"><b>Local-first</b><p class="muted">Scores, missed questions, edits, and imported questions are stored in this browser. Export your bank periodically as a backup.</p></div></main>`}
function openPack(id){state.pack=id;state.view='dashboard';render()}
function nav(){const items=['dashboard','learn','definitions','flashcards','practice','quiz','weak','manage'];return `<div class="nav">${items.map(v=>`<button class="ghost ${state.view==v?'active':''}" onclick="go('${v}')">${({dashboard:'Home',learn:'Learn',definitions:'Definitions',flashcards:'Flashcards',practice:'Practice',quiz:'Quiz',weak:'Weak Areas',manage:'Manage'})[v]}</button>`).join('')}</div>`}
function base(content){let p=packData(state.pack);A.innerHTML=`<main class="shell"><div class="top"><div><button class="ghost" onclick="home()">‹ Packs</button></div><div style="text-align:right"><div class="brand">${esc(p.title)}</div><div class="tag">${esc(p.subtitle)}</div></div></div>${nav()}${content}</main>`}
function go(v){state.view=v;state.quiz=null;state.editingId=null;render()}
function render(){if(!state.pack)return home();let p=packData(state.pack),s=packProgress(state.pack);
 if(state.view==='dashboard'){base(`<div class="grid"><div class="card"><div class="tag">CURRENT MASTERY</div><div class="score">${s.pct}%</div><div class="progress"><span style="width:${s.pct}%"></span></div><p class="muted">${s.correct} correct of ${s.total} answered</p></div><div class="card"><div class="tag">QUESTION BANK</div><div class="metric">${p.questions.length}</div><p class="muted">Passing target: ${p.passing}% · Exam simulation: ${p.examLength} questions</p></div><div class="card"><div class="tag">WEAK AREAS</div><div class="metric">${s.missed.length}</div><p class="muted">Unique questions currently marked for review</p></div></div><h2>Start studying</h2><div class="grid"><div class="card"><h3>Quick Practice</h3><p class="muted">10 mixed questions with immediate explanations.</p><button onclick="startQuiz(10,true,'all')">Start 10</button></div><div class="card"><h3>Exam Simulation</h3><p class="muted">${p.examLength} questions, results shown at the end.</p><button onclick="startQuiz(${p.examLength},false,'all')">Start Exam</button></div><div class="card"><h3>Question Bank Manager</h3><p class="muted">Add, edit, disable, import, export, and back up questions.</p><button onclick="go('manage')">Manage Questions</button></div></div>`)}
 else if(state.view==='learn'){base(`<h1 class="section-title">Learn</h1><p class="muted">Key material organized by category.</p>${p.study.map(c=>`<div class="card category"><h3>${esc(goLabel(c.category))}</h3>${c.bullets.map(b=>`<div class="bullet">${esc(b)}</div>`).join('')}<button class="ghost" onclick="startQuiz(10,true,'${jsEsc(c.id)}')">Practice this category</button></div>`).join('')}`)}
 else if(state.view==='definitions'){base(`<h1 class="section-title">Definitions</h1><input id="search" placeholder="Search terms or definitions" oninput="filterDefs(this.value)"><div id="defs">${defsHTML(p.definitions)}</div>`)}
 else if(state.view==='flashcards'){renderFlash()}
 else if(state.view==='practice'){base(`<h1 class="section-title">Practice</h1><div class="grid"><div class="card"><h3>10 Questions</h3><button onclick="startQuiz(10,true,'all')">Start</button></div><div class="card"><h3>25 Questions</h3><button onclick="startQuiz(25,true,'all')">Start</button></div><div class="card"><h3>50 Questions</h3><button onclick="startQuiz(50,true,'all')">Start</button></div></div><h2>By category</h2><div class="grid">${p.study.map(c=>`<div class="card"><b>${esc(goLabel(c.category))}</b><p class="muted">Focused practice with immediate feedback.</p><button class="ghost" onclick="startQuiz(15,true,'${jsEsc(c.id)}')">Practice</button></div>`).join('')}</div>`)}
 else if(state.view==='quiz'){if(state.quiz)renderQuiz(); else base(`<h1 class="section-title">Quiz Center</h1><div class="grid"><div class="card"><h3>Quick Quiz</h3><p>10 questions</p><button onclick="startQuiz(10,false,'all')">Start</button></div><div class="card"><h3>Standard Quiz</h3><p>25 questions</p><button onclick="startQuiz(25,false,'all')">Start</button></div><div class="card"><h3>Extended Quiz</h3><p>50 questions</p><button onclick="startQuiz(50,false,'all')">Start</button></div><div class="card"><h3>Exam Simulation</h3><p>${p.examLength} questions · ${p.passing}% passing</p><button onclick="startQuiz(${p.examLength},false,'all')">Start Exam</button></div></div>`)}
 else if(state.view==='weak'){let missed=s.missed;let qs=p.questions.filter(q=>missed.includes(q.id));base(`<h1 class="section-title">Weak Areas</h1>${qs.length?`<p class="muted">${qs.length} questions saved for review.</p><button onclick="startWeak()">Practice missed questions</button><div style="height:12px"></div>${[...new Set(qs.map(q=>q.category))].map(c=>`<div class="card category"><h3>${esc(c)}</h3><div class="muted">${qs.filter(q=>q.category===c).length} missed questions</div></div>`).join('')}`:`<div class="card"><h3>No weak areas yet</h3><p class="muted">Take some practice questions. Missed answers will appear here automatically.</p></div>`}`)}
 else if(state.view==='manage'){renderManager()}
}
function defsHTML(defs){return defs.map(d=>`<div class="card definition" data-text="${esc((d.term+' '+d.definition+' '+goLabel(d.category)).toLowerCase())}"><strong>${esc(d.term)}</strong><span class="pill">${esc(goLabel(d.category))}</span><p>${esc(d.definition)}</p></div>`).join('')}
function filterDefs(v){v=v.toLowerCase();document.querySelectorAll('.definition').forEach(x=>x.style.display=x.dataset.text.includes(v)?'block':'none')}
function renderFlash(){let p=packData(state.pack); if(!p.definitions.length)return base('<div class="card">No definitions loaded.</div>'); let d=p.definitions[state.flashIndex%p.definitions.length];base(`<h1 class="section-title">Flashcards</h1><p class="muted">Tap the card to flip it.</p><div class="card flash" onclick="flipFlash()">${state.flashFlip?`<div><div class="def">${esc(d.definition)}</div><p class="muted">${esc(goLabel(d.category))}</p></div>`:`<div><div class="term">${esc(d.term)}</div><p class="muted">Tap for definition</p></div>`}</div><div class="row" style="justify-content:center;margin-top:12px"><button class="ghost" onclick="prevFlash()">Previous</button><span class="pill">${state.flashIndex+1} / ${p.definitions.length}</span><button onclick="nextFlash()">Next</button></div>`)}
function flipFlash(){state.flashFlip=!state.flashFlip;renderFlash()} function nextFlash(){let n=packData(state.pack).definitions.length;state.flashIndex=(state.flashIndex+1)%n;state.flashFlip=false;renderFlash()} function prevFlash(){let n=packData(state.pack).definitions.length;state.flashIndex=(state.flashIndex-1+n)%n;state.flashFlip=false;renderFlash()}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function matchesCategory(q,cat){if(cat==='all')return true;const qn=String(q.category).match(/GO\s*(\d+)/i),cn=String(cat).match(/GO\s*(\d+)/i);if(qn&&cn)return qn[1]===cn[1];return q.category===cat}
function startQuiz(n,immediate,cat){let p=packData(state.pack),pool=p.questions.filter(q=>matchesCategory(q,cat));let qs=shuffle(pool).slice(0,Math.min(n,pool.length));state.view=immediate?'practice':'quiz';state.quiz={qs,index:0,answers:Array(qs.length).fill(null),immediate,locked:false,done:false};renderQuiz()}
function startWeak(){let p=packData(state.pack),s=packProgress(state.pack),qs=shuffle(p.questions.filter(q=>s.missed.includes(q.id)));state.view='practice';state.quiz={qs,index:0,answers:Array(qs.length).fill(null),immediate:true,locked:false,done:false};renderQuiz()}
function answer(i){let z=state.quiz;if(z.locked)return;z.answers[z.index]=i;if(z.immediate)z.locked=true;renderQuiz()}
function nextQ(){let z=state.quiz;if(z.answers[z.index]==null)return;if(z.index<z.qs.length-1){z.index++;z.locked=false;renderQuiz()}else finishQuiz()}
function finishQuiz(){let z=state.quiz,pr=P(),pp=pr[state.pack]||{attempts:[],missed:[]};z.qs.forEach((q,i)=>{let ok=z.answers[i]===q.answer;pp.attempts.push({id:q.id,correct:ok,t:Date.now()});if(ok)pp.missed=(pp.missed||[]).filter(x=>x!==q.id);else if(!(pp.missed||[]).includes(q.id))(pp.missed||=[]).push(q.id)});pr[state.pack]=pp;save(pr);z.done=true;renderQuiz()}
function renderQuiz(){let z=state.quiz,p=packData(state.pack);if(!z)return render();if(z.done){let correct=z.qs.filter((q,i)=>z.answers[i]===q.answer).length,pct=Math.round(correct/z.qs.length*100),pass=pct>=p.passing;let cats=[...new Set(z.qs.map(q=>q.category))];base(`<div class="qbox"><div class="card" style="text-align:center"><div class="tag">FINAL SCORE</div><div class="score ${pass?'pass':'fail'}">${pct}%</div><h2>${pass?'PASS':'KEEP STUDYING'}</h2><p>${correct} of ${z.qs.length} correct</p></div><h2>Category results</h2>${cats.map(c=>{let a=z.qs.map((q,i)=>({q,i})).filter(x=>x.q.category===c),k=a.filter(x=>z.answers[x.i]===x.q.answer).length;return `<div class="card category"><b>${esc(c)}</b><div class="muted">${k}/${a.length} correct · ${Math.round(k/a.length*100)}%</div></div>`}).join('')}<div class="row"><button onclick="go('weak')">Study Weak Areas</button><button class="ghost" onclick="go('dashboard')">Dashboard</button></div></div>`);return}
let q=z.qs[z.index],sel=z.answers[z.index],show=z.immediate&&z.locked;let opts=q.options.map((o,i)=>{let cls='option';if(sel===i)cls+=' selected';if(show&&i===q.answer)cls+=' correct';if(show&&sel===i&&i!==q.answer)cls+=' wrong';return `<button class="${cls}" onclick="answer(${i})">${String.fromCharCode(65+i)}. ${esc(o)}</button>`}).join('');base(`<div class="qbox"><div class="row" style="justify-content:space-between"><span class="pill">Question ${z.index+1} / ${z.qs.length}</span><span class="pill">${esc(q.category)}</span></div><div class="progress" style="margin-top:12px"><span style="width:${((z.index+1)/z.qs.length)*100}%"></span></div><div class="qmeta" style="margin-top:18px">${esc(q.difficulty)} · ${esc(q.type)}</div><div class="question">${esc(q.question)}</div>${opts}${show?`<div class="explain"><b>${sel===q.answer?'Correct':'Not quite'}</b><p>${esc(q.explanation)}</p><div class="tag">Source: ${esc(q.source)}</div></div>`:''}<div class="row" style="justify-content:flex-end;margin-top:16px"><button onclick="nextQ()">${z.index===z.qs.length-1?'Finish':'Next'}</button></div></div>`)}

function categoryOptions(selected){let p=packData(state.pack);let cats=[...new Set(p.questions.map(q=>q.category))].sort();return cats.map(c=>`<option value="${esc(c)}" ${c===selected?'selected':''}>${esc(c)}</option>`).join('')}
function renderManager(){let p=packData(state.pack),qs=p.questions;let cats=[...new Set(qs.map(q=>q.category))].sort();let shown=state.manageFilter==='all'?qs:qs.filter(q=>q.category===state.manageFilter);base(`<div class="topline"><div><h1 class="section-title">Question Bank Manager</h1><p class="muted">${qs.length} active questions. Built-in questions can be edited or disabled; imported and manually added questions can be edited or deleted.</p></div></div><div class="grid"><div class="card"><h3>Add Question</h3><p class="muted">Create a new question directly on your iPad.</p><button onclick="openQuestionForm()">+ New Question</button></div><div class="card"><h3>Import / Export</h3><p class="muted">Move question updates in and out as JSON files.</p><div class="row"><button onclick="document.getElementById('importFile').click()">Import JSON</button><button class="ghost" onclick="exportBank()">Export Bank</button></div><input id="importFile" type="file" accept="application/json,.json" style="display:none" onchange="importBank(event)"></div><div class="card"><h3>Backup</h3><p class="muted">Export includes active questions and can be re-imported on another device.</p><button class="ghost" onclick="exportProgress()">Export Progress</button></div></div><div class="manager-tools"><select onchange="setManageFilter(this.value)"><option value="all">All categories (${qs.length})</option>${cats.map(c=>`<option value="${esc(c)}" ${state.manageFilter===c?'selected':''}>${esc(c)} (${qs.filter(q=>q.category===c).length})</option>`).join('')}</select><input placeholder="Search question text" oninput="managerSearch(this.value)"></div><div id="questionList">${shown.map(questionRow).join('')}</div>`)}
function questionRow(q){return `<div class="card qmanage" data-search="${esc((q.question+' '+q.category+' '+q.source).toLowerCase())}"><div class="row" style="justify-content:space-between"><span class="pill">${esc(q.category)}</span><span class="tag">${esc(q.id)}</span></div><p><b>${esc(q.question)}</b></p><div class="muted small">${esc(q.difficulty)} · ${esc(q.type)} · Source: ${esc(q.source)}</div><div class="row" style="margin-top:12px"><button class="ghost" onclick="openQuestionForm('${jsEsc(q.id)}')">Edit</button><button class="danger" onclick="removeQuestion('${jsEsc(q.id)}')">${isBaseQuestion(q.id)?'Disable':'Delete'}</button></div></div>`}
function setManageFilter(v){state.manageFilter=v;renderManager()}
function managerSearch(v){v=v.toLowerCase();document.querySelectorAll('.qmanage').forEach(x=>x.style.display=x.dataset.search.includes(v)?'block':'none')}
function isBaseQuestion(id){return (D.packs[state.pack].questions||[]).some(q=>q.id===id)}
function rawQuestion(id){const active=allQuestions(state.pack).find(q=>q.id===id);return active||null}
function openQuestionForm(id=null){state.editingId=id;let q=id?rawQuestion(id):null;const def=q||{category:state.pack==='sergeant'?'GO 201 – Response to Resistance':packData(state.pack).categories?.[0]||'',difficulty:'Medium',type:'Knowledge',question:'',options:['','','',''],answer:0,explanation:'',source:''};base(`<h1 class="section-title">${id?'Edit':'New'} Question</h1><div class="card form"><label>Category<select id="fCategory">${categoryOptions(def.category)}</select></label><label>Difficulty<select id="fDifficulty"><option ${def.difficulty==='Easy'?'selected':''}>Easy</option><option ${def.difficulty==='Medium'?'selected':''}>Medium</option><option ${def.difficulty==='Hard'?'selected':''}>Hard</option></select></label><label>Question type<input id="fType" value="${esc(def.type)}"></label><label>Question<textarea id="fQuestion">${esc(def.question)}</textarea></label>${[0,1,2,3].map(i=>`<label>Answer ${String.fromCharCode(65+i)}<textarea id="fOpt${i}">${esc(def.options[i]||'')}</textarea></label>`).join('')}<label>Correct answer<select id="fAnswer">${[0,1,2,3].map(i=>`<option value="${i}" ${def.answer===i?'selected':''}>${String.fromCharCode(65+i)}</option>`).join('')}</select></label><label>Explanation<textarea id="fExplanation">${esc(def.explanation)}</textarea></label><label>Source<input id="fSource" value="${esc(def.source)}" placeholder="Example: GO 210 – Arrests, Stops, and Frisks, §210.4"></label><div class="row"><button onclick="saveQuestionForm()">Save Question</button><button class="ghost" onclick="go('manage')">Cancel</button></div></div>`)}
function saveQuestionForm(){const q={pack:state.pack,category:document.getElementById('fCategory').value,difficulty:document.getElementById('fDifficulty').value,type:document.getElementById('fType').value.trim()||'Knowledge',question:document.getElementById('fQuestion').value.trim(),options:[0,1,2,3].map(i=>document.getElementById('fOpt'+i).value.trim()),answer:Number(document.getElementById('fAnswer').value),explanation:document.getElementById('fExplanation').value.trim(),source:document.getElementById('fSource').value.trim()};if(!q.question||q.options.some(x=>!x)){alert('Please enter the question and all four answer choices.');return}let all=loadCustom(),c=all[state.pack]||{added:[],overrides:{},disabled:[]};if(state.editingId){q.id=state.editingId;if(isBaseQuestion(q.id)){c.overrides=c.overrides||{};c.overrides[q.id]=q}else{c.added=(c.added||[]).map(x=>x.id===q.id?q:x)}}else{q.id=`U${Date.now()}`;c.added=c.added||[];c.added.push(q)}all[state.pack]=c;saveCustom(all);state.editingId=null;state.view='manage';render()}
function removeQuestion(id){if(!confirm(isBaseQuestion(id)?'Disable this built-in question? You can restore built-in questions later by clearing custom data.':'Delete this added question?'))return;let all=loadCustom(),c=all[state.pack]||{added:[],overrides:{},disabled:[]};if(isBaseQuestion(id)){c.disabled=c.disabled||[];if(!c.disabled.includes(id))c.disabled.push(id);if(c.overrides)delete c.overrides[id]}else c.added=(c.added||[]).filter(x=>x.id!==id);all[state.pack]=c;saveCustom(all);renderManager()}
function downloadJSON(obj,name){const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportBank(){downloadJSON({studyforgeVersion:2,pack:state.pack,exportedAt:new Date().toISOString(),questions:allQuestions(state.pack)},`StudyForge_${state.pack}_question_bank.json`)}
function exportProgress(){downloadJSON({studyforgeVersion:2,exportedAt:new Date().toISOString(),progress:P(),customData:loadCustom()},'StudyForge_backup.json')}
function importBank(ev){const file=ev.target.files&&ev.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const obj=JSON.parse(r.result),incoming=Array.isArray(obj)?obj:(obj.questions||[]);if(!Array.isArray(incoming)||!incoming.length)throw new Error('No questions found');let all=loadCustom(),c=all[state.pack]||{added:[],overrides:{},disabled:[]};c.added=c.added||[];c.overrides=c.overrides||{};let count=0;incoming.forEach((q,i)=>{if(!q.question||!Array.isArray(q.options)||q.options.length<4)return;let clean={...q,pack:state.pack,answer:Number(q.answer)};if(!clean.id||isBaseQuestion(clean.id)||c.added.some(x=>x.id===clean.id))clean.id=`IMP${Date.now()}_${i}`;c.added.push(clean);count++});all[state.pack]=c;saveCustom(all);alert(`${count} questions imported.`);renderManager()}catch(e){alert('Import failed: '+e.message)}};r.readAsText(file);ev.target.value=''}

window.openPack=openPack;window.go=go;window.home=home;window.startQuiz=startQuiz;window.startWeak=startWeak;window.answer=answer;window.nextQ=nextQ;window.flipFlash=flipFlash;window.nextFlash=nextFlash;window.prevFlash=prevFlash;window.filterDefs=filterDefs;window.setManageFilter=setManageFilter;window.managerSearch=managerSearch;window.openQuestionForm=openQuestionForm;window.saveQuestionForm=saveQuestionForm;window.removeQuestion=removeQuestion;window.exportBank=exportBank;window.exportProgress=exportProgress;window.importBank=importBank;
home(); if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
